server:
  port: 8081
spring:
  application:
    name: Query

  datasource:
    url: jdbc:postgresql://localhost:5432/queryDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Si es para crear tablas vacías
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
